spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingcloud_customer?createDatabaseIfNotExist=true
    username: rootname
    password: Test@123#123#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect
#    show-sql: true
#  application:
#    name: customer




